services:
  db:
    image: postgres:17
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: unwind
      POSTGRES_PASSWORD: unwind
      POSTGRES_DB: unwind
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: